### PR TITLE
Add $dbport and $default_sort (order) 

### PR DESCRIPTION
**Pull request by tachtler**
- Add $dbport to config file and view
- Add $default_sort to config file and view, with the ability to change the order like hostlookup too.
- Change the README.md too

### CODE REVIEW

**Comment by tachtler** [comment]
Please can you view my pull request and merge or change it like you want.
Thank you for making this project!

**Comment by techsneeze** [comment]
The README and the config sample say that Ascending is default, but sets the default as descending?  I would think this is going to be confusing to people coming in to the project.  It appears as if the actual code DOES assume Ascending, if nothing is set though.

**Comment by tachtler** [comment]
I'm sorry, the copy (settings) were from my original config file. I will correct that.

**Comment by tachtler** [comment]
Hi lwt-pressy,

Greetings back from Lerchenau/Feldmoching to Bogenhausen and thank you for your support and patience with me!

Klaus.

**Pull request merged**
