### PR TITLE
set red color if reject or quarantine

### PR DESCRIPTION
**Pull request by dcaillibaud**

### CODE REVIEW

**Comment by jnew-gh** [comment]
I wanted to discuss this one a bit more, now that the alignment results (#62) has been merged.

It's my understanding that emails are marked as 'none', 'rejected' or 'quarantined' (disposition) because the email reporter followed the policy in the domain's DMARC DNS record (p=none, p=rejected, and p=quarantine, respectively).

So, instead of the test to flag a result being

`disposition is rejected OR disposition is quarantine`

shouldn't the test be

`disposition is different than the domain's policy`

Am I interpreting the DMARC process correctly?

**Comment by trogper** [comment]
Have you considered the pct setting? (percentage)
I think "disposition != policy" test would not be always relevant, as disposition would be "random"

**Comment by jnew-gh** [comment]
Fine. You made me go read the specification. :-)

I'm not sure if you were joking (I don't see a sarcasm sign :-) ), but of course there is no "random" disposition, only "none", "quarantine" and "reject".

Excerpts from the [DMARC RFC](https://tools.ietf.org/html/rfc7489):
>  pct: ... Percentage of messages from the Domain Owner's mail stream to which the DMARC policy is to be applied. However, this MUST NOT be applied to the DMARC-generated reports, all of which must be sent and received unhindered...
[6.3.  General Record Format](https://tools.ietf.org/html/rfc7489#section-6.3)

>  ... If email is subject to the DMARC policy of "quarantine", the Mail Receiver SHOULD quarantine the message...
If email is subject to the DMARC policy of "reject", the Mail Receiver SHOULD reject the message...
[6.6.4.  Message Sampling](https://tools.ietf.org/html/rfc7489#section-6.6.4)

If I read this correctly, the first quote says that the DMARC policy is applied to a certain percentage of messages but then all reports about those messages must be sent. So the reports apply only to those emails considered and don't make a judgement about the rest.

The second quote says the Mail Receiver SHOULD (emphasis is in the RFC) quarantine or reject the message, which begs the question, what if they choose not to? Does a report come through that says, in essence, "We know you said quarantine, but we rejected instead." Will the report read "reject" when the domain owner wanted "quarantine"? Hence the reasoning behind my proposed test.

If some emails followed the policy and some didn't, would there be two different lines (or even three if "none" was applied to some emails) in the report? I don't know. Does anyone have examples where this has happened? I don't unfortunately.

**Comment by trogper** [comment]
My wording was not the best, I did not mean "random" disposition, but randomly chosen, based on the percentage, from "none" and the one in the policy.

I did not read the RFC before either. I agree with you and I will probably say the same as you.
According to "Percentage of messages to which the DMARC policy is to be applied", I suppose all messages are still validated and counted, just they would be exempt from the policy. Then what is unknown is how are they reported.

**Comment by techsneeze** [comment]
I'm going to close this for now, as I think things have evolved a bit and we are a little closer to this concept now.  Feel free to reopen if I'm wrong!  At the very least, conflicts would need to be resolved as a lot of code as changed since this request started.

**Pull request closed without merging**
